### ISSUE TITLE
TypeError: cannot convert dictionary update sequence element #0 to a sequence

### ISSUE THREAD

**Issue by shreekantsh** [spec-first/connexion#909] opened 2019-03-28 10:35 UTC
### Description
When the request body is multipart/related in http POST request. getting following error.

the request body in mycase is a bytes array

"lib/python3.6/site-packages/connexion/operations/openapi.py", line 263, in _get_body_argument
TypeError: cannot convert dictionary update sequence element #0 to a sequence

### Additional info:
Traceback (most recent call last):
  File ".local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File ".local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ".local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File ".local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File ".local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File ".local/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 132, in wrapper
    response = function(request)
  File ".local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 172, in wrapper
    response = function(request)
  File ".local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 346, in wrapper
    return function(request)
  File ".local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File ".local/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 108, in wrapper
    request.files, arguments, has_kwargs, sanitize)
  File ".local/lib/python3.6/site-packages/connexion/operations/abstract.py", line 275, in get_arguments
    has_kwargs, sanitize))
  File ".local/lib/python3.6/site-packages/connexion/operations/openapi.py", line 263, in _get_body_argument
    body_arg.update(body or {})
TypeError: cannot convert dictionary update sequence element #0 to a sequence

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by shreekantsh** [comment] 2019-03-28 10:37
Python version:
Python 3.6.6

Connexion version
Version: 2.0.2
License: Apache License Version 2.0

**Comment by Nicceboy** [comment] 2019-04-14 18:36
I had similar problem. Suggested fix in [issue 892](https://github.com/zalando/connexion/issues/892)
helped in my case, even though it looks like issue's original problem was elsewhere.

**Comment by ddurham2** [comment] 2020-05-22 05:02
@shreekantsh, I know it's been a while, but would you mind checking if the changes in PR #1222 fix your issue?  Do you still have what's needed to check it?

Thanks

**Comment by ddurham2** [comment] 2022-02-18 23:26
closable by my account

**Comment by RobbeSneyders** [comment] 2022-02-19 10:47
Not sure if it is fixed, but since their is no example to reproduce, I'll close it.
Thx @ddurham2.

**Closed by RobbeSneyders** 2022-02-19 10:47 UTC
