### ISSUE TITLE
Post request with empty body but Content Type causes 400 Code

### ISSUE THREAD

**Issue by fr-ser** [spec-first/connexion#1294] opened 2020-09-13 13:28 UTC
### Description

I am developing a backend for a fixed client (grafana simpod json datasource). One of the endpoints is a post request with an empty body (see below). Sadly I always get a 400 code back even though the body is optional.

```yaml
openapi: 3.0.0
info:
  title: Prometheus Grafana API
  version: "0.1"
paths:
  /tag-values:
    post:
      summary: Values for ad hoc filters
      description: returns possible values for ad hoc filters
      operationId: api.endpoints.tag_values
      tags:
        - Ad Hoc Filters
      responses:
        '200':
          description: A valid response
```

### Expected behaviour

```sh
curl --location --request POST 'localhost:3031/tag-values' \
--header 'Content-Type: application/json' \
--data-raw ''
```

Returns: 200

### Actual behaviour

```sh
curl --location --request POST 'localhost:3031/tag-values' \
--header 'Content-Type: application/json' \
--data-raw ''
```

Returns 

```json
{
  "detail": "Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

### Steps to reproduce

A request with an empty body, but with a content type breaks the validation.

This works for example:

```sh
curl --location --request POST 'localhost:3031/tag-values' \
--data-raw ''
```

### Additional info:

Output of the commands:

- `python --version`: 3.8.2
- `pip show connexion | grep "^Version\:"`: Version: 2.7.0

**Comment by RobbeSneyders** [comment] 2023-11-01 16:59
Cannot reproduce on Connexion 3 which will be released tomorrow.

**Closed by RobbeSneyders** 2023-11-01 16:59 UTC
Labels: bug
