### ISSUE TITLE
swagger-ui change URL

### ISSUE THREAD

**Issue by czchen** [spec-first/connexion#887] opened 2019-02-25 08:38 UTC
### Description

We put our connexion application in k8s. But when we access swagger-ui via https://example.com/v0/ui, it is redirected to http://127.0.0.1:5000/v0/ui so we cannot use swagger UI. All other URLs in example.com are not redirected, so we think the problem is in swagger-ui.

### Expected behaviour

When access https://example.com/v0/ui, we shall be about to access swagger-ui

### Actual behaviour

When access https://example.com/v0/ui, we are redirected to http://127.0.0.1:5000/v0/ui.

### Additional info:

Output of the commands:

- `python --version`

$ python --version
Python 3.7.2+

- `pip show connexion | grep "^Version\:"`

$ pip show connexion | grep "^Version\:"
Version: 2.2.0

**Comment by dtkav** [comment] 2019-02-26 05:18
hey @czchen,

Can you please provide the `servers` block of your specification? Also, are you explicitly setting `base_path`?

This may be caused by a trailing-slash redirect. Can you try https://example.com/v0/ui/ (with trailing slash) and let me know if you are still having the issue?

I think the issue may also fixed by #823 - the goal of that diff is to fix connexion behavior when behind a reverse-proxy.

**Comment by czchen** [comment] 2019-02-26 14:57
* The servers block is:
```
servers:
  - url: /v0
```

* I don't set `base_path`
* https://example.com/v0/ui/ does not have this issue.

**Comment by dtkav** [comment] 2019-02-26 21:50
ok, thanks for the info.
Are you using aiohttp or flask?

**Comment by czchen** [comment] 2019-02-27 01:28
flask

**Comment by dtkav** [comment] 2019-03-02 03:02
My guess is that `strict_slashes` in werkzeug is causing a redirect, but it's redirecting to your local IP, not the host you are exposing the site on.

Can you include the output of a verbose `curl` request?
Your original post states that the redirect is from:
>  https://example.com/v0/ui, we are redirected to http://127.0.0.1:5000/v0/ui.
But I would expect the redirected url to include the trailing slash like so:
`https://example.com/v0/ui` redirected to `http://127.0.0.1:5000/v0/ui/`

Also if you have time, can you try out #823 and see if that fixes your issue?
I've been trying to get that merged for a while to fix this type of problem.

**Comment by czchen** [comment] 2019-03-02 03:21
The following is output of `curl --verbose http://exampke.com/v0/ui.

ps. We change our auth sidecar from keycloak-gatekeeper to nginx, the redirect URL is also changed.

```
< HTTP/1.1 301 MOVED PERMANENTLY                   
< Content-Type: text/html; charset=utf-8                      
< Date: Sat, 02 Mar 2019 03:17:04 GMT            
< Location: http://example.com:8080/v0/ui/ 
< Server: nginx/1.13.12                          
< Content-Length: 263                            
< Connection: keep-alive                         
<                                                
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>                    
<h1>Redirecting...</h1>                          
* Connection #0 to host example.com left intact
<p>You should be redirected automatically to target URL: <a href="http://localhost:5000/v0/ui/">http://localhost:5000/v0/ui/</a>.  If not click the link.%       
```

**Comment by dtkav** [comment] 2019-03-07 01:13
> ps. We change our auth sidecar from keycloak-gatekeeper to nginx, the redirect URL is also changed.
Do you have any output to show this behavior?

I think this may be related to your nginx configuration.

I wasn't able to reproduce your issue.
Here's what I did:
```
cd /tmp/
git  clone https://github.com/zalando/connexion.git
cd connexion/
touch Pipfile
pipenv install -e .[swagger-ui]
pipenv shell
cd examples/openapi3/helloworld/
python hello.py
```
After this I tried to access the ui without the trailing slash, and the redirect looks correct to me:
```
✔ ~ > curl -vv localhost:9090/v1.0/ui

*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9090 (#0)
> GET /v1.0/ui HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 301 MOVED PERMANENTLY
< Content-Type: text/html; charset=utf-8
< Content-Length: 267
< Location: http://localhost:9090/v1.0/ui/
< Server: Werkzeug/0.14.1 Python/3.6.7
< Date: Thu, 07 Mar 2019 01:10:14 GMT
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
* Closing connection 0
<p>You should be redirected automatically to target URL: <a href="http://localhost:9090/v1.0/ui/">http://localhost:9090/v1.0/ui/</a>.  If not click the link.
```
```
✔ ~ >curl -vv localtest.me:9090/v1.0/ui

*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localtest.me (127.0.0.1) port 9090 (#0)
> GET /v1.0/ui HTTP/1.1
> Host: localtest.me:9090
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 301 MOVED PERMANENTLY
< Content-Type: text/html; charset=utf-8
< Content-Length: 273
< Location: http://localtest.me:9090/v1.0/ui/
< Server: Werkzeug/0.14.1 Python/3.6.7
< Date: Thu, 07 Mar 2019 01:10:35 GMT
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
* Closing connection 0
<p>You should be redirected automatically to target URL: <a href="http://localtest.me:9090/v1.0/ui/">http://localtest.me:9090/v1.0/ui/</a>.  If not click the link.
```
```
✔ ~ > curl -vv connexion.localtest.me:9090/v1.0/ui

*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to connexion.localtest.me (127.0.0.1) port 9090 (#0)
> GET /v1.0/ui HTTP/1.1
> Host: connexion.localtest.me:9090
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 301 MOVED PERMANENTLY
< Content-Type: text/html; charset=utf-8
< Content-Length: 293
< Location: http://connexion.localtest.me:9090/v1.0/ui/
< Server: Werkzeug/0.14.1 Python/3.6.7
< Date: Thu, 07 Mar 2019 01:10:45 GMT
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
* Closing connection 0
```

**Comment by dtkav** [comment] 2019-03-07 01:15
I've changed the ticket type to `question`.
Feel free to close the ticket. Otherwise, if you post your configuration I can try to help you debug it.

**Closed** 2022-02-20 08:47 UTC
Labels: question

**Comment by maurommx** [comment] 2023-07-21 00:56
![image](https://github.com/spec-first/connexion/assets/24232046/4ce6ca4b-88a1-4ef3-803f-7ade06eb96ac)
url navigator other "server" -> "url", I need update swagger.json > server > url
