### ISSUE TITLE
make swagger.json's uri configurable

### ISSUE THREAD

**Issue by dcolens** [spec-first/connexion#588] opened 2018-05-25 11:31 UTC
Not an issue but a feature request.

Thanks for the work done on connexion, I discovered it recently and like it a lot.

Serving swagger.json from basePath is a problem in my case because basePath is not a unique identifier, for example if basePath is v1.0, I can have multiple services with the same basePath on the same reverse-proxy and the /v1.0/swagger.json is not unique.

One option is to add the /blah/swagger route in the swagger.yaml file and write a handler for it.

It would be nice that connexion exposes an operationId that can be used to return swagger.json making its served path configurable :-)

**Comment by filipmnowak** [comment] 2018-10-09 05:56
exactly the same problem here: reverse proxy / API gateway uses same FQDN and port for all of the services behind it, it differentiates between them via path part of the URL, and indeed basePath is not unique here.

i wonder why Api.add_swagger_json and Api.add_swagger_ui are not governed by the same logic?

can anyone from the maintainers state their opinion about that, what are the options and if PR would be welcome?

**Comment by filipmnowak** [comment] 2018-10-09 06:01
it looks like duplicate of [392](https://github.com/zalando/connexion/issues/392)

**Comment by filipmnowak** [comment] 2018-10-09 10:19
if i got the comment @ [master/connexion/options.py#L35](https://github.com/zalando/connexion/blob/master/connexion/options.py#L35) correctly, swagger.json should be served from `openapi_console_ui_path`/swagger.json, and openapi_console_ui_path can be changed from the default `/ui` with `swagger_url` option. so it seems like intent was to serve swagger.json from the same path as Swagger UI?

**Comment by jmcs** [comment] 2018-12-18 08:01
This should already be possible by [providing the ``openapi_spec_path`` option]( https://github.com/zalando/connexion/blob/44ea9336fe79ddb9592942b405a663d2e3aa612c/connexion/options.py#L91).

**Comment by dtkav** [comment] 2018-12-18 11:02
@jmcs I think this is slightly more subtle.
They need to set the basepath of only the raw_spec (the spec served to swagger_ui), without modifying the spec that was used to generate the application.
This is because as the 'server' connexion should be proxy agnostic, but clients like swagger-ui need to understand the reverse-proxied urls.
I hope that makes sense...

**Closed** 2022-02-19 19:37 UTC
