### ISSUE TITLE
Verify responses from flask error handler

### ISSUE THREAD

**Issue by oalfred** [spec-first/connexion#1422] opened 2021-09-08 14:22 UTC
### Description
I would like to know if there is any way to make connexion verify responses created in a flask error handler.

### Expected behaviour
Responses should be verified, to ensure that they are exactly as defined in the specification.

### Actual behaviour
Responses are not verified, meaning that they may not adhere to the openapi specification.

### Steps to reproduce
I have defined an error response as the default response to one of my endpoints and I have set up a connexion app and attached an error handler to the flask app like this.

```python
import connexion

from my_code import create_error_response

connexion_app = connexion.App(__name__, specification_dir='./', options={'swagger_ui': False})
connexion_app.add_api('openapi.yaml', validate_responses=True)
flask_app = connexion_app.app


@flask_app.errorhandler(Exception)
def handle_unexpected_error(error):
    # do stuff
    error_response = create_error_response()
    return error_response
```

Despite that the error response is defined in my OAS, the function `handle_unexpected_error` can return anything and connexion will not complain. It is totally possible that I'm doing something wrong when setting up this error handling, if so I would appreciate guidance on how to do it correctly.

### Additional info:
python 3.9.6
connexion 2.9.0
flask 1.1.4

**Comment by Ruwann** [comment] 2021-09-16 19:50
There isn't a clear way of doing this at the moment.

I am trying to figure out what the best way would be to link a certain exception or error handler to the relevant response or object from the swagger/openapi yaml, but haven't found a good answer yet. In your example, it wouldn't be clear from which operation this error handler was called? So perhaps I'm overlooking something, but we aren't sure which response to validate against.

**Comment by oalfred** [comment] 2021-09-20 09:11
Well, for my case, at least as long as we are in the error handler itself, I would think it is possible to get the necessary information from flask's request object, which contains the path and method of the API call. However, my knowledge of these matters is limited and I have not looked into the connexion code, so I can't judge whether it is possible to rely on the request object in a general situation.

**Comment by RobbeSneyders** [comment] 2022-02-19 23:05
Closing as duplicate of #797.

**Closed by RobbeSneyders** 2022-02-19 23:05 UTC
