### ISSUE TITLE
g object is not accessible in x-bearerInfoFunc

### ISSUE THREAD

**Issue by gaurav-triverus** [spec-first/connexion#1881] opened 2024-02-14 20:45 UTC
### Description
with connexio3.0 upgrade, x-bearerInfoFunc is executing before before_request. in this case flask g object is not accessible in x-bearerInfoFunc.

### Expected behaviour
currently we are at connexion 2.14 version and upgrading it to the latest version.
in x-bearerInfoFunc after validating the token, we are validating the user in database too.
we are creating a db session in before_request and then commiting and close the session in after_request. in previous version before_request is being executed before x-bearerInfoFunc. so the flask g object and db session is available in x-bearerInfoFunc.

### Additional info:

Output of the commands:

- `python --version`
   Python 3.9.18
- `pip show connexion | grep "^Version\:"`
   Version: 3.0.5

**Comment by RobbeSneyders** [comment] 2024-02-14 23:40
Duplicate of #1880. Please check my answer [there](https://github.com/spec-first/connexion/issues/1880#issuecomment-1945033127).

**Closed by RobbeSneyders** 2024-02-14 23:40 UTC
