### ISSUE TITLE
Force parameter validation in an endpoint without parameters

### ISSUE THREAD

**Issue by jmorenov** [spec-first/connexion#1705] opened 2023-05-05 07:04 UTC
### Description
In my application I have several exposed endpoints that do not have any parameters

### Expected behaviour
When I activate strict_validation I understand that it should validate this endpoint if any user accesses these endpoints with any parameter and return a 400, since none is expected by definition.

### Actual behaviour
But what is happening is that it performs the request correctly and returns a 200. The only option I have found is to define a false parameter not required and then start validating.

### Steps to reproduce
- Create an application with api spec:
```
app = connexion.AsyncApp(__name__, specification_dir="spec")
app.add_api("openapi.yaml", strict_validation=True)
``` 
- Add to openapi.yaml some method GET without parameters
- Access this endpoint with some parameter
- You will get a correct respo

### Additional info:

The problem is coming from here:
File: connexion/operations/abstract.py

```
    @property
    def __validation_decorators(self):
        """
        :rtype: types.FunctionType
        """
        ParameterValidator = self.validator_map['parameter']
        RequestBodyValidator = self.validator_map['body']
        if self.parameters:
            yield ParameterValidator(self.parameters,
                                     self.api,
                                     strict_validation=self.strict_validation)
        if self.body_schema:
            yield RequestBodyValidator(self.body_schema, self.consumes, self.api,
                                       is_nullable(self.body_definition),
                                       strict_validation=self.strict_validation)

```

If the method does not have parameters, it has not ParameterValidator

**Comment by Ruwann** [comment] 2023-06-09 15:26
Which version of connexion are you using?
It seems you are using the `AsyncApp` but the linked snippet is from v2.

For 3.x, I can't seem to reproduce the issue, an endpoint without parameters and strict validation raises the error as expected:
```json
{"type": "about:blank", "title": "Bad Request", "detail": "Extra query parameter(s) foo not in spec", "status": 400}
```

**Comment by jmorenovfever** [comment] 2023-06-12 10:53
Yes, we are using the version: 2.14.1 because is the latest stable. When will be stable the version 3?

**Comment by RobbeSneyders** [comment] 2023-11-01 16:03
Connexion 3 will be released tomorrow.

**Closed by RobbeSneyders** 2023-11-01 16:03 UTC
Labels: v2
