### ISSUE TITLE
When null json literal is valid JSON input, any invalid input passes the validation

### ISSUE THREAD

**Issue by Budovi** [spec-first/connexion#1295] opened 2020-09-13 18:05 UTC
### Description
When accepting a `null` JSON literal in a `requestBody` (this may affect other places, but I know about this one), any invalid JSON payload passes (and the value is interpreted as `null`.

```yaml
...
paths:
  /foo:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              nullable: true
...
```
In the above example, if I post an invalid JSON to the endpoint, for example
```
bar
```
this is not a valid JSON (for the "bar" to be a string it must be quoted). However, this passes just like `null` was provided instead.

### Expected behaviour
The `BadRequestProblem(detail="Request body is not valid JSON")` is raised and 400 returned.

### Actual behaviour
This silently passes `null` (`None` in Python) to the endpoint's body.

### Steps to reproduce
Just follow the description.

### Additional info:
This is another bug caused by treating None as a special return value, when, in fact, it is a valid option in the JSON context. I believe this is caused by the handling inside `RequestBodyValidator.__call__(self, function)` where the following code inside a wrapper function can be found:
```python
                data = request.json

                empty_body = not(request.body or request.form or request.files)
                if data is None and not empty_body and not self.is_null_value_valid:
                    try:
                        ctype_is_json = is_json_mimetype(request.headers.get("Content-Type", ""))
                    except ValueError:
                        ctype_is_json = False

                    if ctype_is_json:
                        # Content-Type is json but actual body was not parsed
                        raise BadRequestProblem(detail="Request body is not valid JSON")
                    else:
                        # the body has contents that were not parsed as JSON
                        raise UnsupportedMediaTypeProblem(
                                       "Invalid Content-type ({content_type}), expected JSON data".format(
                                           content_type=request.headers.get("Content-Type", "")
                                       ))
```
The erroneous input is not caught since `request.json` is `None` and `self.is_null_value_valid` is `True`, completely omitting the check. Any ideas on how to go about this issue and not break everything else?

I'm using Python 3.8 and Connexion 2.7.0.

**Comment by RobbeSneyders** [comment] 2023-11-01 16:58
Cannot reproduce on Connexion 3 which will be released tomorrow.

**Closed by RobbeSneyders** 2023-11-01 16:58 UTC
